name: kachpara
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.8.9+133

environment:
  sdk: ">=2.18.0"

dependency_overrides:
  stripe_android: "9.5.0+1"

dependencies:
  dotted_line: ^3.1.0
  qr_flutter: ^4.0.0
  bloc_concurrency: ^0.2.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.0.6
  coupon_uikit: ^0.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.3
  firebase_analytics: ^10.2.1
  firebase_app_check: ^0.2.1+3
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.1.1
  firebase_dynamic_links: ^5.1.0
  firebase_messaging: ^14.4.1
  firebase_storage: ^11.6.6
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_google_places: ^0.3.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.0.3
  geocoding: ^2.1.1
  geolocator: ^9.0.2
  get_it: ^7.2.0
  go_router: ^12.1.0
  google_maps_flutter: ^2.2.7
  http: ^0.13.5
  image_picker: ^1.0.7
  injectable: ^1.5.4
  intl: ^0.18.1
  intl_phone_field: ^3.1.0
  location: ^5.0.3
  lottie: ^2.7.0
  maps_launcher: ^2.2.0
  nfc_manager: ^3.3.0
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  place_picker: ^0.10.0
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  time_picker_widget: ^1.0.0+10
  url_launcher: ^6.0.20
  flutter_stripe: 9.6.0
  qr_code_dart_scan: ^0.8.0
  webview_flutter: ^4.7.0
  visibility_detector: ^0.4.0+2
  tap_debouncer: ^2.2.0

dev_dependencies:
  
  build_runner: ^2.2.1
  flutter_contacts: ^1.1.5
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.3
  flutter_switch: ^0.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockito: ^5.3.2
  shared_preferences: ^2.2.2
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/cards/
    - assets/lottie/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#ffffff"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
