default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "225G44WRK9",
      issuer_id: "69a6de94-98b1-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_225G44WRK9.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    upload_to_testflight
  end
end